# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.2.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-07-22T22:05:11Z"
  labels:
    app: my-project-pod
  name: my-project-pod
spec:
  containers:
  - args:
    - mysqld
    command:
    - docker-entrypoint.sh
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: GPG_KEYS
      value: 177F4010FE56CA3336300305F1656F24C74CD1D8
    - name: MARIADB_VERSION
      value: 1:10.5.8+maria~focal
    - name: MYSQL_DATABASE
      value: my_project
    - name: MYSQL_USER
      value: web
    - name: MYSQL_PASSWORD
      value: web
    - name: MYSQL_ROOT_PASSWORD
      value: root
    - name: GOSU_VERSION
      value: "1.12"
    - name: MARIADB_MAJOR
      value: "10.5"
    image: docker.io/library/mariadb:10.5.8
    name: my-db
    ports:
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: c8b59f5e8fbd7eb1d1bccb6c9fbe156f26142d77498dc8d9f9007185a92dea9c-pvc
    workingDir: /
  - args:
    - nginx
    - -g
    - daemon off;
    command:
    - /docker-entrypoint.sh
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: NJS_VERSION
      value: 0.6.1
    - name: PKG_RELEASE
      value: 1~buster
    - name: NGINX_VERSION
      value: 1.21.1
    image: docker.io/library/nginx:latest
    name: nginx
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /etc/nginx/conf.d/default.conf
      name: var-home-johnm-development-web-podman-symfony-pod-container-site.conf-host-0
    - mountPath: /var/www/html/app
      name: var-home-johnm-development-web-podman-symfony-pod-host-1
    workingDir: /
  - args:
    - php-fpm
    command:
    - docker-php-entrypoint
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: PHP_VERSION
      value: 7.4.21
    - name: PHP_CFLAGS
      value: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
    - name: PHP_INI_DIR
      value: /usr/local/etc/php
    - name: PHP_CPPFLAGS
      value: -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
    - name: PHP_URL
      value: https://www.php.net/distributions/php-7.4.21.tar.xz
    - name: PHP_SHA256
      value: cf43384a7806241bc2ff22022619baa4abb9710f12ec1656d0173de992e32a90
    - name: GPG_KEYS
      value: 42670A7FE4D0441C8E4632349E4FDC074A4EF02D 5A52880781F755608BF815FC910DEB46F53EA312
    - name: PHP_EXTRA_CONFIGURE_ARGS
      value: --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi
    - name: PHPIZE_DEPS
      value: "autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake
        \t\tpkg-config \t\tre2c"
    - name: PHP_ASC_URL
      value: https://www.php.net/distributions/php-7.4.21.tar.xz.asc
    - name: PHP_LDFLAGS
      value: -Wl,-O1 -pie
    image: localhost/web:latest
    name: my-web-base
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /var/www/html/app
      name: var-home-johnm-development-web-podman-symfony-pod-host-0
    - mountPath: /usr/local/etc/php/conf.d/container-php-ext-xdebug.ini
      name: var-home-johnm-development-web-podman-symfony-pod-container-xdebug.ini-host-1
    workingDir: /var/www/html/app
  dnsConfig: {}
  restartPolicy: Never
  volumes:
  - name: c8b59f5e8fbd7eb1d1bccb6c9fbe156f26142d77498dc8d9f9007185a92dea9c-pvc
    persistentVolumeClaim:
      claimName: c8b59f5e8fbd7eb1d1bccb6c9fbe156f26142d77498dc8d9f9007185a92dea9c
  - hostPath:
      path: /var/home/johnm/development/web/podman-symfony-pod/container/site.conf
      type: File
    name: var-home-johnm-development-web-podman-symfony-pod-container-site.conf-host-0
  - hostPath:
      path: /var/home/johnm/development/web/podman-symfony-pod
      type: Directory
    name: var-home-johnm-development-web-podman-symfony-pod-host-1
  - hostPath:
      path: /var/home/johnm/development/web/podman-symfony-pod
      type: Directory
    name: var-home-johnm-development-web-podman-symfony-pod-host-0
  - hostPath:
      path: /var/home/johnm/development/web/podman-symfony-pod/container/xdebug.ini
      type: File
    name: var-home-johnm-development-web-podman-symfony-pod-container-xdebug.ini-host-1
status: {}

